name: Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGISTRY_LOCATION: europe-west1
  REGISTRY_REPOSITORY: ${{ secrets.REGISTRY_REPOSITORY }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: europe-west1
  APP_NAME: meme-web-app

jobs:
  build-push-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Docker Auth
      run: |-
        gcloud auth configure-docker ${{ env.REGISTRY_LOCATION }}-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |-
        docker build -t "${{ env.REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_REPOSITORY }}/${{ env.APP_NAME }}:${{ github.sha }}" .
        docker push "${{ env.REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_REPOSITORY }}/${{ env.APP_NAME }}:${{ github.sha }}"

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Install Helm
      uses: azure/setup-helm@v4.2.0

    - name: Deploy to GKE
      run: |-
        helm upgrade --install ${{ env.APP_NAME }} ./etc/chart \
          --set image.repository=${{ env.REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_REPOSITORY }}/${{ env.APP_NAME }} \
          --set image.tag=${{ github.sha }} \
          --set projectId=${{ secrets.GCP_PROJECT_ID }} \
          --set secrets.gcp_project_id=${{ secrets.GCP_PROJECT_ID }} \
          --set secrets.pubsub_topic_id=${{ secrets.PUBSUB_TOPIC_ID }} \
          --wait